# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72fe89fa5f8a65d893dae5462fe27b03f0891107d5882d13a605d2b9fae316f7df8a444a65dce33200ae6b2ec01713819514a5b29f00a6dec877947c7357fb03

test:
  secret_key_base: 931170c176cbc24968d66b363d3729c4748d56dc5fc15773cb39fe798e98c14e5ce34da077fba67f586b2364cbea0c0be544412d936e230d4a52e9c354e62c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
